#!/usr/bin/env python3
"""Runs the real AcademicTask against an offline, deterministic Android/lifecycle shell."""
import pathlib, subprocess, sys, tempfile
root = pathlib.Path(__file__).resolve().parents[1]
jar = pathlib.Path(sys.argv[1]).resolve()
sources = {
'android/content/Context.java': '''package android.content; public class Context { public static final String INPUT_METHOD_SERVICE="input"; public Object getSystemService(String key){return null;} }''',
'android/app/Activity.java': '''package android.app; public class Activity extends android.content.Context { public boolean finishing,destroyed; public boolean isFinishing(){return finishing;} public boolean isDestroyed(){return destroyed;} }''',
'android/graphics/Bitmap.java': 'package android.graphics; public class Bitmap {}',
'android/net/http/SslError.java': 'package android.net.http; public class SslError {}',
'android/net/Uri.java': 'package android.net; public class Uri {private final String value; public Uri(String v){value=v;} public String toString(){return value;} }',
'android/os/Looper.java': 'package android.os; public class Looper {public static Looper getMainLooper(){return new Looper();}}',
'android/os/Handler.java': '''package android.os; import java.util.*; public class Handler {public static final List<Handler> all=new ArrayList<>(); public final List<Runnable> jobs=new ArrayList<>(); public Handler(Looper l){all.add(this);} public void postDelayed(Runnable r,long ms){jobs.add(r);} public void removeCallbacksAndMessages(Object o){jobs.clear();} public static void fire(){for(Handler h:new ArrayList<>(all))for(Runnable r:new ArrayList<>(h.jobs))r.run();} public static int pending(){return all.stream().mapToInt(h->h.jobs.size()).sum();} }''',
'android/view/View.java': '''package android.view; public class View {public static final int IMPORTANT_FOR_ACCESSIBILITY_AUTO=0,IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS=4; public float alpha=1; public boolean focus=true; public ViewGroup parent; public Object getParent(){return parent;} public void setAlpha(float n){alpha=n;} public void setFocusable(boolean b){focus=b;} public void setFocusableInTouchMode(boolean b){focus=b;} public void setImportantForAccessibility(int n){} public void clearFocus(){} public Object getWindowToken(){return null;} }''',
'android/view/ViewGroup.java': '''package android.view; import java.util.*; public class ViewGroup extends View {public final List<View> children=new ArrayList<>(); public void addView(View v,int i,Object p){if(v.parent!=null)throw new IllegalStateException("already attached");children.add(i,v);v.parent=this;} public void removeView(View v){children.remove(v);v.parent=null;} }''',
'android/view/inputmethod/InputMethodManager.java': 'package android.view.inputmethod; public class InputMethodManager {public void hideSoftInputFromWindow(Object t,int f){}}',
'android/widget/FrameLayout.java': 'package android.widget; public class FrameLayout extends android.view.ViewGroup {public static class LayoutParams {public LayoutParams(int w,int h){}} }',
'android/webkit/WebSettings.java': '''package android.webkit; public class WebSettings {public static final int MIXED_CONTENT_NEVER_ALLOW=1; public void setJavaScriptEnabled(boolean b){} public void setDomStorageEnabled(boolean b){} public void setAllowFileAccess(boolean b){} public void setAllowContentAccess(boolean b){} public void setMixedContentMode(int n){} public void setSafeBrowsingEnabled(boolean b){} public void setSupportMultipleWindows(boolean b){} public void setJavaScriptCanOpenWindowsAutomatically(boolean b){} public void setBuiltInZoomControls(boolean b){} public void setDisplayZoomControls(boolean b){} public void setLoadWithOverviewMode(boolean b){} public void setUseWideViewPort(boolean b){} }''',
'android/webkit/CookieManager.java': 'package android.webkit; public class CookieManager {public static CookieManager getInstance(){return new CookieManager();} public void setAcceptCookie(boolean b){} public void setAcceptThirdPartyCookies(WebView w,boolean b){} public void flush(){} }',
'android/webkit/WebView.java': '''package android.webkit; import java.util.*; public class WebView extends android.view.View {public static final List<WebView> all=new ArrayList<>(); public WebViewClient client; public boolean destroyed,stopped; public String url; public WebView(android.app.Activity a){all.add(this);} public WebSettings getSettings(){return new WebSettings();} public void setWebViewClient(WebViewClient c){client=c;} public void loadUrl(String u){url=u;} public void stopLoading(){stopped=true;} public void destroy(){destroyed=true;} }''',
'android/webkit/WebViewClient.java': '''package android.webkit; public class WebViewClient {public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest r){return false;} public void onPageStarted(WebView w,String u,android.graphics.Bitmap b){} public void onPageFinished(WebView w,String u){} public void onReceivedSslError(WebView w,SslErrorHandler h,android.net.http.SslError e){} public void onReceivedError(WebView w,WebResourceRequest r,WebResourceError e){} public void onReceivedHttpError(WebView w,WebResourceRequest r,WebResourceResponse e){} }''',
'android/webkit/SslErrorHandler.java': 'package android.webkit; public class SslErrorHandler {public boolean cancelled;public void cancel(){cancelled=true;}}',
'android/webkit/WebResourceError.java': 'package android.webkit; public class WebResourceError {}',
'android/webkit/WebResourceRequest.java': '''package android.webkit; public class WebResourceRequest {private final boolean main; public WebResourceRequest(boolean b){main=b;} public boolean isForMainFrame(){return main;} public android.net.Uri getUrl(){return new android.net.Uri("https://webvpn2.hitwh.edu.cn/");}}''',
'android/webkit/WebResourceResponse.java': 'package android.webkit; public class WebResourceResponse {private final int code;public WebResourceResponse(int c){code=c;}public int getStatusCode(){return code;}}',
'edu/hitwh/fieldnote/Vault.java': 'package edu.hitwh.fieldnote; final class Vault {}',
'edu/hitwh/fieldnote/PortalActivity.java': 'package edu.hitwh.fieldnote; final class PortalActivity {static boolean allowed(String s){return s.startsWith("https://webvpn2.hitwh.edu.cn/");}}',
'edu/hitwh/fieldnote/SchoolLogin.java': '''package edu.hitwh.fieldnote; import java.util.*; import java.util.function.*; import android.webkit.WebView; final class SchoolLogin {static final List<SchoolLogin> all=new ArrayList<>(); final Consumer<String> status,blocked; final Runnable ready; boolean deferred,closed; int opens; SchoolLogin(android.content.Context c,android.app.Activity a,WebView w,Vault v,String target,boolean interactive,Consumer<String> s,Consumer<Boolean> surface,Consumer<String> b,Runnable r){status=s;blocked=b;ready=r;all.add(this);} SchoolLogin deferVerification(){deferred=true;return this;} void pageStarted(){} void pageFinished(){} void pause(String m){blocked.accept(m);} void openVerification(){opens++;} void close(){closed=true;} }''',
'edu/hitwh/fieldnote/Enhancements.java': '''package edu.hitwh.fieldnote; import java.util.*; import org.json.*; import android.webkit.WebView; final class Enhancements {interface Callback {void done(JSONObject result);} static final class Sync {interface Progress {void update(String stage,int percent);} static final List<Sync> all=new ArrayList<>(); final Callback cb; final Progress observer; final android.widget.FrameLayout parent; WebView web; boolean ended; Sync(android.app.Activity a,android.widget.FrameLayout p,Callback c,Progress o){parent=p;cb=c;observer=o;all.add(this);} static boolean requiresLogin(JSONObject o){return o.optBoolean("authenticate");} void start(JSONObject s){web=new WebView(null);parent.addView(web,0,null);if(s.optBoolean("immediate"))end(new JSONObject().put("status","pending").put("message","pending").put("results",new JSONArray()));} void end(JSONObject r){if(ended)return;ended=true;if(web!=null){parent.removeView(web);web.destroy();}cb.done(r);} void cancel(){end(new JSONObject().put("status","cancelled").put("results",new JSONArray()));} } }''',
'edu/hitwh/fieldnote/AcademicTaskLifecycleTest.java': '''package edu.hitwh.fieldnote;
import org.json.*; import java.util.*; import android.app.Activity; import android.os.Handler; import android.view.View; import android.webkit.*; import android.widget.FrameLayout;
public final class AcademicTaskLifecycleTest {
 static int checks; static void check(boolean v,String label){checks++;if(!v)throw new AssertionError(label);}
 static JSONObject state(boolean auth){return new JSONObject().put("authenticate",auth).put("studentId","synthetic").put("password","synthetic-only");}
 static JSONObject result(String status){return new JSONObject().put("status",status).put("message",status).put("results",new JSONArray());}
 static class Run {Activity activity=new Activity();FrameLayout frame=new FrameLayout();List<JSONObject> done=new ArrayList<>();AcademicTask task;
  Run(){Handler.all.clear();WebView.all.clear();SchoolLogin.all.clear();Enhancements.Sync.all.clear();frame.addView(new View(),0,null);task=new AcademicTask(activity,frame,new Vault(),r->{check(WebView.all.stream().allMatch(w->w.destroyed),"callback follows WebView cleanup");done.add(r);});}
  SchoolLogin login(){return SchoolLogin.all.get(SchoolLogin.all.size()-1);} Enhancements.Sync sync(){return Enhancements.Sync.all.get(Enhancements.Sync.all.size()-1);} WebView web(){return WebView.all.get(WebView.all.size()-1);}
 }
 public static void main(String[] args){
  Run r=new Run();r.task.start(state(true),true);check(r.task.snapshot().optBoolean("busy"),"login stays busy");check(r.login().deferred,"verification is deferred");check(r.frame.children.get(0)==r.web()&&r.web().alpha==0&&!r.web().focus,"hidden browser is below main UI");check(Enhancements.Sync.all.isEmpty(),"no queries before login");r.task.verify();check(r.login().opens==0,"no unsolicited verification");r.login().pause("需要验证");check(r.task.snapshot().optBoolean("needsVerification")&&r.task.snapshot().optInt("progress")==-1,"verification waits without popup");check(r.login().opens==0,"blocked does not open browser");r.task.verify();check(r.login().opens==1&&!r.task.snapshot().optBoolean("needsVerification"),"explicit click opens browser");r.login().pause("已关闭验证");check(r.task.snapshot().optBoolean("needsVerification")&&!r.activity.finishing,"closing verification keeps task and activity");WebView authWeb=r.web();SchoolLogin login=r.login();login.ready.run();check(authWeb.destroyed&&login.closed,"login web closes before query stage");check(Enhancements.Sync.all.size()==1,"queries start once");r.sync().observer.update("正在读取考试",50);check(r.task.snapshot().optInt("progress")==70,"query stage estimates mapped");r.sync().end(result("read"));check(r.done.size()==1&&!r.task.snapshot().optBoolean("busy")&&r.task.snapshot().optInt("progress")==100,"normal completion delivered once");check(Handler.pending()==0,"normal completion clears timeout");r.task.cancel();check(r.done.size()==1,"late cancel cannot repeat callback");
  r=new Run();r.task.start(state(true),true);login=r.login();r.task.cancel();login.ready.run();check(r.done.size()==1&&Enhancements.Sync.all.isEmpty(),"late login success after cancellation ignored");check(Handler.pending()==0,"cancel clears timeout");
  r=new Run();r.task.start(state(false),true);r.task.cancel();check(r.done.size()==1,"sync cancel callback cannot reenter completion");
  r=new Run();r.task.start(state(false),true);r.sync().end(result("login"));check(SchoolLogin.all.size()==1,"expired query hands off once");r.login().ready.run();r.sync().end(result("login"));check(SchoolLogin.all.size()==1&&r.done.size()==1&&r.done.get(0).optString("status").equals("login"),"no relogin loop after ready");
  r=new Run();r.task.start(state(true),false);check(SchoolLogin.all.isEmpty(),"allowLogin=false bypasses authentication");r.sync().end(result("login"));check(r.done.size()==1&&SchoolLogin.all.isEmpty(),"disabled auth stays disabled on failed query");
  r=new Run();r.task.start(state(true),true);r.task.start(state(true),true);check(SchoolLogin.all.size()==1,"start is idempotent");r.login().pause("需要验证");Handler.fire();check(r.done.size()==1&&r.done.get(0).optString("status").equals("timeout"),"verification timeout becomes terminal");check(Handler.pending()==0&&!r.task.snapshot().optBoolean("needsVerification"),"timeout clears timer and verification state");
  r=new Run();r.task.start(state(true),true);WebView w=r.web();w.client.onReceivedError(w,new WebResourceRequest(false),new WebResourceError());check(r.done.isEmpty(),"subresource failure does not cancel login");w.client.onReceivedHttpError(w,new WebResourceRequest(true),new WebResourceResponse(503));check(r.done.size()==1&&r.done.get(0).optString("message").contains("503"),"real HTTP error ends once without retry");
  r=new Run();r.task.start(state(true),true);w=r.web();w.client.onReceivedHttpError(w,new WebResourceRequest(true),new WebResourceResponse(403));check(r.done.isEmpty()&&r.task.snapshot().optBoolean("needsVerification")&&r.login().opens==0,"403 waits for explicit verification");r.task.cancel();
  r=new Run();r.task.start(state(true),true);w=r.web();SslErrorHandler ssl=new SslErrorHandler();w.client.onReceivedSslError(w,ssl,new android.net.http.SslError());check(ssl.cancelled&&r.done.size()==1,"TLS failure never bypassed");
  r=new Run();r.task.start(state(false).put("immediate",true),true);check(r.done.size()==1&&Handler.pending()==0,"synchronous setup result cleans up before callback");
  System.out.println("AcademicTask lifecycle: "+checks+" offline checks passed");
 }
}'''
}
with tempfile.TemporaryDirectory(prefix='xixu-academic-task-') as work:
    workspace = pathlib.Path(work)
    files = []
    for name, text in sources.items():
        p = workspace / name; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text); files.append(str(p))
    classes = workspace / 'classes'; classes.mkdir()
    subprocess.run(['java','--add-modules','jdk.compiler','com.sun.tools.javac.Main','-cp',str(jar),'-d',str(classes),*files,str(root / 'app/src/main/java/edu/hitwh/fieldnote/AcademicTask.java')],check=True)
    subprocess.run(['java','-cp',str(classes)+':'+str(jar),'edu.hitwh.fieldnote.AcademicTaskLifecycleTest'],check=True)
