#!/usr/bin/env python3
"""Offline event-order regression tests for the actual Android NewsCrawler source."""
import ast, pathlib, subprocess, sys, tempfile
root=pathlib.Path(__file__).resolve().parents[1]
jar=pathlib.Path(sys.argv[1]).resolve()
# Reuse the small Android shell used by the academic task tests, without executing that test.
module=ast.parse((root/'tests/academic-task-lifecycle.py').read_text())
sources=ast.literal_eval(next(n.value for n in module.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='sources' for t in n.targets)))
sources.pop('edu/hitwh/fieldnote/AcademicTaskLifecycleTest.java')
sources.update({
'android/content/Context.java': '''package android.content; public class Context {public static final String INPUT_METHOD_SERVICE="input"; public Context getApplicationContext(){return this;} public android.content.res.AssetManager getAssets(){return new android.content.res.AssetManager();} public android.content.res.Resources getResources(){return new android.content.res.Resources();} public Object getSystemService(String s){return null;} }''',
'android/content/res/AssetManager.java': '''package android.content.res; public class AssetManager {public java.io.InputStream open(String s){return new java.io.ByteArrayInputStream(new byte[0]);}}''',
'android/content/res/Resources.java': '''package android.content.res; public class Resources {public android.util.DisplayMetrics getDisplayMetrics(){return new android.util.DisplayMetrics();}}''',
'android/util/DisplayMetrics.java': 'package android.util; public class DisplayMetrics {public float density=1;}',
'android/net/Uri.java': '''package android.net; public class Uri {private final java.net.URI u;private Uri(java.net.URI v){u=v;}public static Uri parse(String s){return new Uri(java.net.URI.create(s));} public String getHost(){return u.getHost();}public String getScheme(){return u.getScheme();}public String getUserInfo(){return u.getRawUserInfo();}public int getPort(){return u.getPort();}public String getPath(){return u.getPath();}public String getEncodedPath(){return u.getRawPath();}public String toString(){return u.toString();}public Builder buildUpon(){return new Builder(u);}public static class Builder {java.net.URI u;Builder(java.net.URI x){u=x;}public Builder clearQuery(){return this;}public Builder fragment(String s){return this;}public Uri build(){try{return new Uri(new java.net.URI(u.getScheme(),u.getRawUserInfo(),u.getHost(),u.getPort(),u.getRawPath(),null,null));}catch(Exception e){throw new RuntimeException(e);}}}}''',
'android/net/http/SslError.java': 'package android.net.http; public class SslError {public String getUrl(){return "https://webvpn2.hitwh.edu.cn/";}}',
'android/os/Looper.java': 'package android.os; public class Looper {static final Looper MAIN=new Looper();public static Looper getMainLooper(){return MAIN;}public static Looper myLooper(){return MAIN;}}',
'android/os/Handler.java': '''package android.os;import java.util.*;public class Handler {public static final List<Handler> all=new ArrayList<>();record Job(Runnable run,long delay){}final List<Job> jobs=new ArrayList<>();public Handler(Looper l){all.add(this);}public void post(Runnable r){r.run();}public void postDelayed(Runnable r,long ms){jobs.add(new Job(r,ms));}public void removeCallbacksAndMessages(Object o){jobs.clear();}public static void tick(){for(Handler h:new ArrayList<>(all))for(Job j:new ArrayList<>(h.jobs))if(j.delay<=1200){h.jobs.remove(j);j.run.run();}}}''',
'android/webkit/WebChromeClient.java': 'package android.webkit;public class WebChromeClient {}',
'android/webkit/WebView.java': '''package android.webkit;import java.util.*;import java.util.function.*;public class WebView extends android.view.View {public static final List<WebView> all=new ArrayList<>();public final List<String> loads=new ArrayList<>();public String url,response;public WebViewClient client;public boolean destroyed;public WebView(android.content.Context a){all.add(this);}public WebSettings getSettings(){return new WebSettings();}public void setWebViewClient(WebViewClient c){client=c;}public void setWebChromeClient(WebChromeClient c){}public String getUrl(){return url;}public void loadUrl(String u){url=u;loads.add(u);}public void stopLoading(){}public void destroy(){destroyed=true;}public void onResume(){}public void onPause(){}public void evaluateJavascript(String s,Consumer<String> c){if(response!=null)c.accept(response);} }''',
'android/webkit/WebResourceRequest.java': '''package android.webkit;public class WebResourceRequest {String url;public WebResourceRequest(String u){url=u;}public boolean isForMainFrame(){return true;}public String getMethod(){return "GET";}public android.net.Uri getUrl(){return android.net.Uri.parse(url);}}''',
'edu/hitwh/fieldnote/Vault.java': 'package edu.hitwh.fieldnote;final class Vault {Vault(android.content.Context c){}}',
'edu/hitwh/fieldnote/Enhancements.java': 'package edu.hitwh.fieldnote;final class Enhancements {static String read(java.io.InputStream s,int n){return "(function(){})";}}',
})
sources['android/view/View.java']=sources['android/view/View.java'].replace('public Object getWindowToken()', 'public void setEnabled(boolean b){}public void setClickable(boolean b){}public void measure(int w,int h){}public void layout(int l,int t,int r,int b){}public static class MeasureSpec {public static final int EXACTLY=1;public static int makeMeasureSpec(int n,int mode){return n;}} public Object getWindowToken()')
sources['android/webkit/WebSettings.java']=sources['android/webkit/WebSettings.java'].replace('public static final int MIXED_CONTENT_NEVER_ALLOW', 'public void setLoadsImagesAutomatically(boolean b){}public void setBlockNetworkImage(boolean b){}public static final int MIXED_CONTENT_NEVER_ALLOW')
sources['edu/hitwh/fieldnote/SchoolLogin.java']=sources['edu/hitwh/fieldnote/SchoolLogin.java'].replace('void pageStarted()', 'void active(boolean b){}String diagnostics(){return "{}";}void pageStarted()')
sources['edu/hitwh/fieldnote/NewsCrawlerLifecycleTest.java']='''package edu.hitwh.fieldnote;
import java.lang.reflect.*;import java.util.*;import org.json.*;import android.app.Activity;import android.widget.FrameLayout;import android.webkit.*;import android.os.Handler;
public final class NewsCrawlerLifecycleTest {
 static int checks;static final String PATH="/2026/0928/c12a123/page.htm",V="https://webvpn2.hitwh.edu.cn/http/abc"+PATH,P="https://news.hitwh.edu.cn"+PATH;
 static void check(boolean ok,String message){checks++;if(!ok)throw new AssertionError(message);}
 static Object field(NewsCrawler c,String name)throws Exception{Field f=NewsCrawler.class.getDeclaredField(name);f.setAccessible(true);return f.get(c);}
 static void set(NewsCrawler c,String name,Object value)throws Exception{Field f=NewsCrawler.class.getDeclaredField(name);f.setAccessible(true);f.set(c,value);}
 static Object call(NewsCrawler c,String name,Object...args)throws Exception{Class<?>[] types=new Class<?>[args.length];for(int i=0;i<args.length;i++)types[i]=args[i] instanceof Boolean?boolean.class:String.class;Method m=NewsCrawler.class.getDeclaredMethod(name,types);m.setAccessible(true);return m.invoke(c,args);}
 static class Run {NewsCrawler c;WebView w;List<JSONObject> done=new ArrayList<>();List<String> errors=new ArrayList<>();Run()throws Exception{Handler.all.clear();WebView.all.clear();Activity a=new Activity();c=new NewsCrawler(a,a,new FrameLayout(),Set.of(),s->{},done::add,errors::add);c.start();w=WebView.all.get(0);w.loads.clear();w.url=V;set(c,"loggedIn",true);set(c,"homeUrl","https://webvpn2.hitwh.edu.cn/http/home/");set(c,"current",new JSONObject().put("id","hitwh-home:a123").put("url",V).put("publicUrl",P).put("title","synthetic").put("published","2026-09-28"));set(c,"visited",1);((Set<String>)field(c,"discoveredUrls")).add(V);}
 void error(String u){w.client.onReceivedHttpError(w,new WebResourceRequest(u),new WebResourceResponse(503));}
 }
 public static void main(String[] args)throws Exception{
  Run r=new Run();r.error(V);check((boolean)field(r.c,"waitingNext"),"fallback paces without second queue item");check((int)field(r.c,"visited")==1&&(int)field(r.c,"skipped")==0,"fallback does not double count attempts");int version=(int)field(r.c,"navigationVersion");r.w.client.onPageStarted(r.w,V,null);check((int)field(r.c,"navigationVersion")==version,"late page start cannot invalidate scheduled fallback");r.error(V);Handler.tick();check(r.w.loads.equals(List.of(P)),"one public fallback is loaded");r.error(V);check((int)field(r.c,"skipped")==0&&r.done.isEmpty(),"late VPN error ignored after public fallback starts");r.error(P);check(r.done.size()==1&&r.done.get(0).optInt("visited")==1&&r.done.get(0).optInt("skipped")==1,"public failure counts once and completes");check(r.w.destroyed,"terminal cleanup destroys browser");
  r=new Run();r.error(V);r.c.active(false);Handler.tick();check(r.w.loads.isEmpty(),"paused fallback does not request");r.c.active(true);Handler.tick();check(r.w.loads.equals(List.of(P)),"resume loads same public article");check((int)field(r.c,"visited")==1,"resume does not skip or double count current article");r.c.cancel();
  r=new Run();r.error(V);r.c.cancel();Handler.tick();check(r.w.loads.isEmpty()&&r.w.destroyed&&r.done.isEmpty(),"cancel prevents queued public request and success callback");
  r=new Run();JSONObject item=(JSONObject)field(r.c,"current");item.put("publicUrl","https://news.hitwh.edu.cn/2026/0928/c12a999/page.htm");r.error(V);check(r.done.size()==1&&r.w.loads.isEmpty(),"fallback cannot substitute another article path");
  r=new Run();item=(JSONObject)field(r.c,"current");item.put("publicUrl","https://example.invalid"+PATH);r.error(V);check(r.done.size()==1&&r.w.loads.isEmpty(),"fallback cannot leave exact official host set");
  r=new Run();((ArrayDeque<JSONObject>)field(r.c,"pending")).add(new JSONObject().put("id","hitwh-home:a124").put("url",V.replace("a123","a124")));((Set<String>)field(r.c,"discoveredUrls")).add(V.replace("a123","a124"));call(r.c,"pageFailed","学校需要验证",false);Handler.tick();check(r.w.loads.equals(List.of(V.replace("a123","a124"))),"permission failure skips article and reads next without public fallback");check((int)field(r.c,"skipped")==1&&(int)field(r.c,"visited")==2,"permission failure counters remain consistent");r.c.cancel();
  r=new Run();r.error(V);Handler.tick();check((boolean)call(r.c,"allowedNavigation",P),"allow discovered same public article");check(!(boolean)call(r.c,"allowedNavigation",P.replace("https:","http:")),"reject actual HTTP downgrade");check(!(boolean)call(r.c,"allowedNavigation",P.replace("a123","a999")),"reject different article redirect");check((boolean)call(r.c,"allowedNavigation",P.replace("page.htm","page.psp")),"allow same-article WebPlus alias");r.c.cancel();
  System.out.println("NewsCrawler lifecycle: "+checks+" offline checks passed");
 }
}'''
with tempfile.TemporaryDirectory(prefix='xixu-news-crawler-') as work:
    workspace=pathlib.Path(work);files=[]
    for name,text in sources.items():
        p=workspace/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text);files.append(str(p))
    classes=workspace/'classes';classes.mkdir()
    subprocess.run(['java','--add-modules','jdk.compiler','com.sun.tools.javac.Main','-cp',str(jar),'-d',str(classes),*files,str(root/'app/src/main/java/edu/hitwh/fieldnote/NewsCrawler.java')],check=True)
    subprocess.run(['java','-cp',str(classes)+':'+str(jar),'edu.hitwh.fieldnote.NewsCrawlerLifecycleTest'],check=True)
