const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const A=require('../app/src/main/assets/core.js'),S=require('../app/src/main/assets/startup.js');
const cell=text=>({text,rowSpan:1,colSpan:1});
const grid=text=>({pages:[{tables:[{rows:[[Object.assign(cell(''),{colSpan:2}),...['一','二','三','四','五','六','日'].map(d=>cell('星期'+d))],['上午','1-2',text,'','','','','',''].map(cell)]}]}]});
const result=snapshot=>({kind:'courses',term:'2026秋季',sourceKey:'hitwh-v1-courses',verifiedSchool:true,snapshot,capturedAt:1,host:'webvpn2.hitwh.edu.cn'});
test('学校紧凑课表拆分教师地点并合并多个周次段',()=>{const p=A.parseSnapshot(grid('测试课程\n教师甲[18]周，[4，5，7-17]周\nA楼-101'),'courses').records[0];assert.equal(p.teacher,'教师甲');assert.equal(p.room,'A楼-101');assert.deepEqual(p.weeks,[4,5,7,8,9,10,11,12,13,14,15,16,17,18]);assert.equal(p.day,1);assert.equal(p.endPeriod,2);});
test('同行教室自动提取，未给地点不猜造',()=>{assert.equal(A.parseSnapshot(grid('测试课程\n教师甲[4，5，7-18]周B楼-202'),'courses').records[0].room,'B楼-202');assert.equal(A.parseSnapshot(grid('体育\n教师乙[1-5，7-17]周'),'courses').records[0].room,'');});
test('首次一键同步无需预先手动导入',()=>{const next=S.planUpdate([],result(grid('测试课程\n教师甲[4，5]周A楼-101')));assert.equal(next.data.length,1);assert.equal(next.data[0].teacher,'教师甲');});
test('旧版缺字段条目迁移，不重复追加，保留其他学期',()=>{const s=grid('测试课程\n教师甲[4，5]周A楼-101');const old={...A.parseSnapshot(s,'courses').records[0],id:'old',term:'2026秋季',teacher:'',room:''};const p=S.planUpdate([old,{...old,id:'previous',term:'2025秋季'}],result(s));assert.equal(p.data.length,2);assert.equal(p.data.find(x=>x.term==='2026秋季').room,'A楼-101');assert.ok(p.data.some(x=>x.id==='previous'));});
test('已手动修正的课不被覆盖或重复，新课程仍更新',()=>{const s=grid('测试课程\n教师甲[4，5]周A楼-101');const old={...A.parseSnapshot(s,'courses').records[0],id:'custom',term:'2026秋季',manualOverride:true,room:'自定义教室'};const p=S.planUpdate([old],result(s));assert.equal(p.data.length,1);assert.equal(p.data[0].room,'自定义教室');assert.equal(p.meta.manualPreserved,1);});
test('已确认的学校空考试表保留缓存并报告空结果',()=>{const s={pages:[{tables:[{rows:[['课程名称','考试具体时间','考试地点','座位号'].map(cell)]}]}]};const r={...result(s),kind:'exams',sourceKey:'hitwh-v1-exams'},old=[{id:'cached'}];const p=S.planUpdate(old,r);assert.deepEqual(p.data,old);assert.equal(p.meta.empty,true);});
test('学校成绩优先最终成绩，缺失绩点不从学分绩推算',()=>{const s={pages:[{tables:[{rows:[['课程名称','总成绩','最终成绩','学分','参与学分绩'].map(cell),['测试课程','85','90','3','是'].map(cell)]}]}]};const p=A.parseSnapshot(s,'grades').records[0];assert.equal(p.score,'90');assert.equal(p.point,null);});
const prepare=fs.readFileSync(require.resolve('../app/src/main/assets/prepare-query.js'),'utf8');
function page(kind,selected,options=['2026秋季'],pathname){let clicks=0,changes=0;const select={value:selected,options:options.map(text=>({textContent:text,value:text})),getClientRects:()=>[{}],dispatchEvent:()=>changes++};const button={textContent:'查 询',getClientRects:()=>[{}],click:()=>clicks++};const doc={querySelectorAll:s=>s==='select'?[select]:s==='a,button'?[button]:[]};return{run:term=>JSON.parse(vm.runInNewContext(prepare,{document:doc,location:{pathname:pathname||({courses:'/kbcx/queryGrkb',exams:'/kscx/queryKcForXs',grades:'/cjcx/queryQmcj'})[kind]},Event:class{}})(kind,term)),counts:()=>({clicks,changes,value:select.value})};}
test('课表当前学期就绪时不重复发起查询',()=>{const p=page('courses','2026秋季');assert.equal(p.run('2026–2027 秋季').state,'ready');assert.equal(p.counts().clicks,0);});
test('成绩选择当前学期且只提交一次；未提供学期不猜测',()=>{const p=page('grades','');assert.equal(p.run('2026–2027 秋季').state,'submitted');assert.deepEqual(p.counts(),{clicks:1,changes:0,value:'2026秋季'});const q=page('grades','','2026秋季'.split());assert.equal(q.run('2025秋季').state,'term');assert.equal(q.counts().clicks,0);});
test('学年中的春季映射到第二年；登录页不触发查询',()=>{const p=page('exams','',['2027春季']);assert.equal(p.run('2026–2027 春季').state,'submitted');const q=page('courses','2026秋季',['2026秋季'],'/login');assert.equal(q.run('2026秋季').state,'login');assert.equal(q.counts().clicks,0);});
