#!/usr/bin/env python3
"""Offline JVM state/call tests for production NewsClient + NewsCrawler.
Android boundaries, SchoolLogin, Vault and model I/O are test doubles. This does
not test Android WebView rendering, dialogs, JobScheduler or real sign-in.
Usage: python3 tools/test-news-client.py /path/to/android.jar /path/to/json.jar
"""
from pathlib import Path
import subprocess
import sys

root = Path(__file__).resolve().parents[1]
if len(sys.argv) != 3:
    raise SystemExit(__doc__)
android, json = (str(Path(p).resolve()) for p in sys.argv[1:])
build = root / 'build/offline-news-client-tests'
source = build / 'stubs'
classes = build / 'classes'
source.mkdir(parents=True, exist_ok=True)
classes.mkdir(parents=True, exist_ok=True)
# Keep stubs deliberately small: record calls/state; never implement a browser or network.
stubs = {
'android/os/Looper': '''public class Looper { static final Looper MAIN=new Looper(); static final Thread OWNER=Thread.currentThread(); public static Looper getMainLooper(){return MAIN;} public static Looper myLooper(){return Thread.currentThread()==OWNER?MAIN:null;} }''',
'android/os/Handler': '''public class Handler { private static final java.util.Queue<Runnable> READY=new java.util.concurrent.ConcurrentLinkedQueue<>(); private final java.util.List<Runnable> delayed=new java.util.ArrayList<>(); public Handler(Looper l){} public boolean post(Runnable r){READY.add(r);return true;} public boolean postDelayed(Runnable r,long delay){delayed.add(r);return true;} public void removeCallbacks(Runnable r){READY.remove(r);delayed.remove(r);} public void removeCallbacksAndMessages(Object t){delayed.clear();} public static void drain(){Runnable r;while((r=READY.poll())!=null)r.run();} }''',
'android/os/PersistableBundle': '''public class PersistableBundle { public void putLong(String k,long v){} }''',
'android/os/Build': '''public class Build { public static class VERSION { public static final int SDK_INT=35; } }''',
'android/content/Context': '''public class Context { public int starts; public final android.app.job.JobScheduler scheduler=new android.app.job.JobScheduler(); public final android.app.NotificationManager notifications=new android.app.NotificationManager(); public Context getApplicationContext(){return this;} public <T>T getSystemService(Class<T> c){return c.cast(c==android.app.job.JobScheduler.class?scheduler:notifications);} public android.content.res.AssetManager getAssets(){return new android.content.res.AssetManager();} public android.content.res.Resources getResources(){return new android.content.res.Resources();} public int checkSelfPermission(String p){return 0;} public void startActivity(Intent i){starts++;} }''',
'android/content/Intent': '''public class Intent { public static final int FLAG_ACTIVITY_CLEAR_TOP=1,FLAG_ACTIVITY_SINGLE_TOP=2; public Intent(Context c,Class<?> t){} public Intent setAction(String a){return this;} public Intent putExtra(String k,boolean b){return this;} public Intent addFlags(int f){return this;} }''',
'android/content/ComponentName': '''public class ComponentName { public ComponentName(Context c,Class<?> t){} }''',
'android/content/res/AssetManager': '''public class AssetManager { public java.io.InputStream open(String name){return new java.io.ByteArrayInputStream("/* offline script stub */".getBytes(java.nio.charset.StandardCharsets.UTF_8));} }''',
'android/content/res/Resources': '''public class Resources { public android.util.DisplayMetrics getDisplayMetrics(){return new android.util.DisplayMetrics();} }''',
'android/util/DisplayMetrics': '''public class DisplayMetrics { public float density=1; }''',
'android/app/Activity': '''public class Activity extends android.content.Context { public android.view.View content; @SuppressWarnings("unchecked") public <T extends android.view.View>T findViewById(int id){return (T)content;} }''',
'android/app/NotificationManager': '''public class NotificationManager { public static final int IMPORTANCE_DEFAULT=3; public int shown,cancelled; public void cancel(int id){cancelled++;} public boolean areNotificationsEnabled(){return true;} public void createNotificationChannel(NotificationChannel c){} public void notify(int id,Notification n){shown++;} }''',
'android/app/job/JobScheduler': '''public class JobScheduler { JobInfo job; public void cancel(int id){job=null;} public JobInfo getPendingJob(int id){return job;} public int schedule(JobInfo j){job=j;return 1;} }''',
'android/app/job/JobInfo': '''public class JobInfo { public static final int NETWORK_TYPE_ANY=1; public boolean isPeriodic(){return false;} public static class Builder { public Builder(int id,android.content.ComponentName c){} public Builder setRequiredNetworkType(int n){return this;} public Builder setMinimumLatency(long n){return this;} public Builder setPersisted(boolean b){return this;} public Builder setExtras(android.os.PersistableBundle b){return this;} public JobInfo build(){return new JobInfo();} } }''',
'android/view/View': '''public class View { public static final int IMPORTANT_FOR_ACCESSIBILITY_AUTO=0,IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS=4; public float alpha=1; public boolean enabled=true,clickable,focusable,focusableTouch; public int accessibility; public ViewGroup parent; public void setAlpha(float f){alpha=f;} public void setEnabled(boolean b){enabled=b;} public void setClickable(boolean b){clickable=b;} public void setFocusable(boolean b){focusable=b;} public void setFocusableInTouchMode(boolean b){focusableTouch=b;} public void setImportantForAccessibility(int i){accessibility=i;} public void clearFocus(){} public Object getParent(){return parent;} public void measure(int w,int h){} public void layout(int a,int b,int c,int d){} public static class MeasureSpec { public static final int EXACTLY=1; public static int makeMeasureSpec(int s,int m){return s;} } }''',
'android/view/ViewGroup': '''public class ViewGroup extends View { public final java.util.List<View> children=new java.util.ArrayList<>(); public void removeView(View v){children.remove(v);v.parent=null;} }''',
'android/widget/FrameLayout': '''public class FrameLayout extends android.view.ViewGroup { public FrameLayout(android.content.Context c){} public static class LayoutParams { public LayoutParams(int w,int h){} } public void addView(android.view.View v,int i,LayoutParams p){children.add(i,v);v.parent=this;} }''',
'android/webkit/WebSettings': '''public class WebSettings { public static final int MIXED_CONTENT_NEVER_ALLOW=1; public boolean blockImages,loadImages; public void setJavaScriptEnabled(boolean b){} public void setDomStorageEnabled(boolean b){} public void setAllowFileAccess(boolean b){} public void setAllowContentAccess(boolean b){} public void setMixedContentMode(int m){} public void setSafeBrowsingEnabled(boolean b){} public void setSupportMultipleWindows(boolean b){} public void setJavaScriptCanOpenWindowsAutomatically(boolean b){} public void setLoadWithOverviewMode(boolean b){} public void setUseWideViewPort(boolean b){} public void setLoadsImagesAutomatically(boolean b){loadImages=b;} public void setBlockNetworkImage(boolean b){blockImages=b;} }''',
'android/webkit/CookieManager': '''public class CookieManager { static final CookieManager I=new CookieManager(); public static CookieManager getInstance(){return I;} public void setAcceptCookie(boolean b){} public void setAcceptThirdPartyCookies(WebView w,boolean b){} }''',
'android/webkit/WebChromeClient': '''public class WebChromeClient {}''',
'android/webkit/WebViewClient': '''public class WebViewClient { public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return false;} public void onPageStarted(WebView v,String s,android.graphics.Bitmap b){} public void onPageFinished(WebView v,String s){} public void onReceivedSslError(WebView v,SslErrorHandler h,android.net.http.SslError e){} public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){} public void onReceivedHttpError(WebView v,WebResourceRequest r,WebResourceResponse e){} }''',
'android/webkit/WebView': '''public class WebView extends android.view.View { public static int created; public static WebView last; public String url; public boolean destroyed; public WebViewClient client; public ValueCallback<String> callback; public final WebSettings settings=new WebSettings(); public WebView(android.content.Context c){created++;last=this;} public WebSettings getSettings(){return settings;} public void setWebChromeClient(WebChromeClient c){} public void setWebViewClient(WebViewClient c){client=c;} public void loadUrl(String u){url=u;if(client!=null){client.onPageStarted(this,u,null);client.onPageFinished(this,u);}} public String getUrl(){return url;} public void evaluateJavascript(String s,ValueCallback<String> cb){callback=cb;} public void respond(org.json.JSONObject data){ValueCallback<String> cb=callback;callback=null;cb.onReceiveValue(org.json.JSONObject.quote(data.toString()));} public void stopLoading(){} public void destroy(){destroyed=true;} public void onResume(){} public void onPause(){} }''',
'android/net/Uri': '''public class Uri { final java.net.URI u; Uri(java.net.URI u){this.u=u;} public static Uri parse(String s){return new Uri(java.net.URI.create(s));} public String getScheme(){return u.getScheme();} public String getHost(){return u.getHost();} public String getEncodedPath(){return u.getRawPath();} public String getPath(){return u.getPath();} public int getPort(){return u.getPort();} public String getUserInfo(){return u.getUserInfo();} public String toString(){return u.toString();} public Builder buildUpon(){return new Builder(this);} public static class Builder { final Uri original; Builder(Uri u){original=u;} public Builder clearQuery(){return this;} public Builder fragment(String s){return this;} public Uri build(){try{return new Uri(new java.net.URI(original.u.getScheme(),original.u.getRawAuthority(),original.u.getRawPath(),null,null));}catch(Exception e){throw new IllegalArgumentException(e);}} } }''',
'edu/hitwh/fieldnote/Vault': '''final class Vault { static org.json.JSONObject data=new org.json.JSONObject(); Vault(android.content.Context c){} synchronized org.json.JSONObject load(){synchronized(Vault.class){return new org.json.JSONObject(data.toString());}} interface Edit {void apply(org.json.JSONObject o)throws Exception;} void update(Edit edit)throws Exception {synchronized(Vault.class){org.json.JSONObject next=load();edit.apply(next);data=next;}} }''',
'edu/hitwh/fieldnote/SchoolLogin': '''final class SchoolLogin { static SchoolLogin last; final java.util.function.Consumer<String> blocked; final Runnable ready; final java.util.function.Consumer<Boolean> surface; final boolean interactive; boolean deferred,closed; int opened; SchoolLogin(android.content.Context c,android.app.Activity a,android.webkit.WebView w,Vault v,String target,boolean allow,java.util.function.Consumer<String> status,java.util.function.Consumer<Boolean> surface,java.util.function.Consumer<String> blocked,Runnable ready){last=this;this.blocked=blocked;this.ready=ready;this.surface=surface;interactive=allow;} SchoolLogin deferVerification(){deferred=true;return this;} void openVerification(){opened++;surface.accept(true);} void active(boolean b){} void pageStarted(){} void pageFinished(){} void close(){closed=true;} String diagnostics(){return "offline login boundary";} }''',
'edu/hitwh/fieldnote/LocalNews': '''final class LocalNews { static java.util.concurrent.CountDownLatch entered,release; static class Failure extends Exception {} static org.json.JSONObject select(org.json.JSONObject config,org.json.JSONArray articles,long now)throws Exception {if(entered!=null){entered.countDown();release.await();} return new org.json.JSONObject().put("articles",new org.json.JSONArray()).put("processedIds",new org.json.JSONArray()).put("warnings",new org.json.JSONArray()).put("context",new org.json.JSONObject());} }''',
'edu/hitwh/fieldnote/Enhancements': '''final class Enhancements { static String read(java.io.InputStream in,int limit)throws Exception{return new String(in.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);} }''',
'edu/hitwh/fieldnote/PortalActivity': '''final class PortalActivity { static boolean allowed(String s){return s.startsWith("https://webvpn2.hitwh.edu.cn/");} }''',
'edu/hitwh/fieldnote/MainActivity': '''final class MainActivity extends android.app.Activity {}''',
'edu/hitwh/fieldnote/NewsSyncJob': '''final class NewsSyncJob {}''',
'edu/hitwh/fieldnote/R': '''final class R { static class drawable {static final int ic_launcher=1;} }''',
}
files = []
for name, body in stubs.items():
    path = source / (name + '.java')
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('package ' + name.rsplit('/', 1)[0].replace('/', '.') + ';\n' + body + '\n')
    files.append(str(path))
production = root / 'app/src/main/java/edu/hitwh/fieldnote'
files += [str(production / (name + '.java')) for name in ('NewsClient', 'NewsCrawler', 'NewsData', 'NewsCache', 'LocalNewsPolicy')]
files.append(str(root / 'tests/NewsClientFlowTest.java'))
subprocess.run(['java', '--add-modules', 'jdk.compiler', 'com.sun.tools.javac.Main', '-Xlint:unchecked', '-cp', json + ':' + android, '-d', str(classes), *files], check=True)
subprocess.run(['java', '-cp', str(classes) + ':' + json + ':' + android, 'edu.hitwh.fieldnote.NewsClientFlowTest'], check=True)
